services:
  server_session:
    container_name: server_session
    build:
      context:
        cmd/server_session/
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}

  mongo:
    container_name: mongo
    restart:
      always
    logging:
      options:
        max-size: 1g
    image: mongo
    ports:
      - "27020:27017"
